name: BiocCheck

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  bioccheck:
    runs-on: ubuntu-latest
    container:
      image: bioconductor/bioconductor_docker:devel

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install R Package Dependencies
        run: |
          Rscript -e "BiocManager::install(c('BiocCheck', 'covr', 'lintr'))"

      - name: Build Package
        run: R CMD build .

      - name: Run BiocCheck
        run: |
          PACKAGE_TAR=$(ls *.tar.gz)
          Rscript -e "BiocCheck::BiocCheck('$PACKAGE_TAR')"

      - name: Run R CMD check
        run: |
          PACKAGE_TAR=$(ls *.tar.gz)
          R CMD check $PACKAGE_TAR

      - name: Test Coverage
        run: Rscript -e "covr::codecov()"

      - name: Lint Code
        run: Rscript -e "lintr::lint_package()"

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage-badge.svg
